#!/usr/bin/env bash
#PBS -P dg9 -q normal -l wd,walltime=4:00:00,mem=10GB,ncpus=1,storage=scratch/dg9+gdata/v10+gdata/dg9+gdata/up71+gdata/fj7
source /g/data/dg9/env
eval $(workflow_params)
master=$(ls -1 *.SLC_tab | sort | head -1 | sed -e 's/^\([0-9]\{8\}\).*/\1/')
mkdir -p ../geo ../rslc ../diff0
rm -f ../geo/* ../rslc/* ../diff0/*
cp ${master}.hgt ../geo/${master}_dem.rdc
dem_coord dem.dem_par ../geo/${master}.lon ../geo/${master}.lat
cp $cwd/*.rslc $cwd/*.rslc.par ../rslc/
cp $cwd/*.diff ../diff0/
for f in $(ls $cwd/../rslc/*.rslc.par | grep -v ${master}); do
  ff=$(basename $f)
  base_orbit $cwd/../rslc/${master}.rslc.par ${f} $cwd/../diff0/${master}_${ff/.rslc.par/.base};
done
